export const BUSINESS_AUTH_BOOTSTRAP_FINISHED = 'BUSINESS_AUTH_BOOTSTRAP_FINISHED';
export const BUSINESS_AUTH_LOGIN_FAILED = 'BUSINESS_AUTH_LOGIN_FAILED';
export const BUSINESS_AUTH_LOGIN_STARTED = 'BUSINESS_AUTH_LOGIN_STARTED';
export const BUSINESS_AUTH_LOGIN_SUCCEEDED = 'BUSINESS_AUTH_LOGIN_SUCCEEDED';
export const BUSINESS_AUTH_LOGOUT = 'BUSINESS_AUTH_LOGOUT';
export const CLEAR_PENDING_BUSINESS_AUTH_NAVIGATION = 'CLEAR_PENDING_BUSINESS_AUTH_NAVIGATION';
export const SET_PENDING_BUSINESS_AUTH_NAVIGATION = 'SET_PENDING_BUSINESS_AUTH_NAVIGATION';
